### PR TITLE
Use upstream index handler

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
Current status:
```
Unexpected index: got={[/.well-known/oauth-authorization-server /api /api/v1 /apis /apis/apps 
/apis/apps/v1beta1 /apis/authentication.k8s.io /apis/authentication.k8s.io/v1beta1 /apis/autoscaling 
/apis/autoscaling/v1 /apis/batch /apis/batch/v1 /apis/batch/v2alpha1 /apis/certificates.k8s.io 
/apis/certificates.k8s.io/v1alpha1 /apis/extensions /apis/extensions/v1beta1 /apis/policy 
/apis/policy/v1beta1 /apis/storage.k8s.io /apis/storage.k8s.io/v1beta1 /controllers /healthz 
/healthz/ping /healthz/poststarthook/bootstrap-controller /healthz/poststarthook/extensions/third-party-resources
/healthz/ready /metrics /oapi /oapi/v1 /osapi /swaggerapi/ /version /version/openshift]}, 
expected=[/api /api/v1 /apis /controllers /healthz /healthz/ping /healthz/ready /metrics /oapi /oapi/v1 /swaggerapi/]
```

**Comment by ncdc** [comment]
Here's what the ncdc/kubernetes openshift-1.5 branch shows:

```
curl -k https://localhost:6443
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1beta1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1alpha1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/extensions/third-party-resources",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/logs",
    "/metrics",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
```

**Comment by sttts** [comment]
So we are not that far from upstream. This strange .well-known.... name is wrong and /version is missing.

**Comment by ncdc** [comment]
I'd recommend checking kube master too just to see how it currently stands

**Comment by sttts** [comment]
What about this `/.well-known/oauth-authorization-server`? It's our metadata oauth endpoint. Should we list that? From its shape it looks like we shouldn't.

**Comment by ncdc** [comment]
I assume not

**Comment by sttts** [comment]
We have this now:
```
/api
/api/v1
/apis
/apis/apps
/apis/apps/v1beta1
/apis/authentication.k8s.io
/apis/authentication.k8s.io/v1beta1
/apis/autoscaling
/apis/autoscaling/v1
/apis/batch
/apis/batch/v1
/apis/batch/v2alpha1
/apis/certificates.k8s.io
/apis/certificates.k8s.io/v1alpha1
/apis/extensions
/apis/extensions/v1beta1
/apis/policy
/apis/policy/v1beta1
/apis/storage.k8s.io
/apis/storage.k8s.io/v1beta1
/controllers
/healthz
/healthz/ping
/healthz/poststarthook/bootstrap-controller
/healthz/poststarthook/extensions/third-party-resources
/healthz/ready
/metrics
/oapi
/oapi/v1
/osapi
/swaggerapi/
/version
/version/openshift
```

**Comment by ncdc** [comment]
@smarterclayton is this ^^^^ ok for `GET /` in origin?

**Comment by sttts** [comment]
And it is not protected, in contrast to kube.

**Comment by sttts** [comment]
@smarterclayton ^^

**Pull request merged**
